# This file was generated by GoReleaser. DO NOT EDIT.
cask "weeks" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "5d3ac180dc522a8af1363c5f39b05a427462c80bc109822facc7dcde94923cc1"
      url "https://github.com/weeks-app/weeks-cli/releases/download/v#{version}/weeks_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "11bb958909ddb6afd7a9526dbdf6ee04adba3198988503cb210970fc683779a6"
      url "https://github.com/weeks-app/weeks-cli/releases/download/v#{version}/weeks_#{version}_darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c4f479c4cb0130fdebb7d07de8a02ef20837fc050aa32d9d6f4342406c4bdb9f"
      url "https://github.com/weeks-app/weeks-cli/releases/download/v#{version}/weeks_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "289de42e2d2c1cf5bbdce3c7b279daa7a6adca11d901b4829c7bfb9b058a30db"
      url "https://github.com/weeks-app/weeks-cli/releases/download/v#{version}/weeks_#{version}_linux_x86_64.tar.gz"
    end
  end

  name "weeks"
  desc "Command-line and agent interface to Weeks"
  homepage "https://weeks.app"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "weeks"

  # No zap stanza required
end
