# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Weeks < Formula
  desc "Command-line and agent interface to Weeks"
  homepage "https://weeks.app"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/weeks-app/weeks-cli/releases/download/v0.1.2/weeks_0.1.2_darwin_x86_64.tar.gz"
      sha256 "8dc6577e20552e5c9d18e9becde2905dad06f136d2d6465c8edb7b338f473bf0"

      define_method(:install) do
        bin.install "weeks"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/weeks-app/weeks-cli/releases/download/v0.1.2/weeks_0.1.2_darwin_arm64.tar.gz"
      sha256 "37c66f8b8c73b9d2e04b02bcfddf194da4c3111ddf3c82f02ba322c2e42f80ec"

      define_method(:install) do
        bin.install "weeks"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/weeks-app/weeks-cli/releases/download/v0.1.2/weeks_0.1.2_linux_x86_64.tar.gz"
      sha256 "c6dbb7e1c4ef1b6782eff516b1c3691e228ca88f84c37f49e8fe52ab67bd3781"
      define_method(:install) do
        bin.install "weeks"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/weeks-app/weeks-cli/releases/download/v0.1.2/weeks_0.1.2_linux_arm64.tar.gz"
      sha256 "9f4104ac5c70245772a9bc62a50d196121df7559dd3ebaea556f748c128bb119"
      define_method(:install) do
        bin.install "weeks"
      end
    end
  end

  test do
    system "#{bin}/weeks", "version"
  end
end
