# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Weeks < Formula
  desc "Command-line and agent interface to Weeks"
  homepage "https://weeks.app"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/weeks-app/weeks-cli/releases/download/v0.1.1/weeks_0.1.1_darwin_x86_64.tar.gz"
      sha256 "38bbfa8ba6038b063de720f335ff19c10cd64d76496ea9dc47cfb1213aee8e7b"

      define_method(:install) do
        bin.install "weeks"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/weeks-app/weeks-cli/releases/download/v0.1.1/weeks_0.1.1_darwin_arm64.tar.gz"
      sha256 "3f14ca56c58b6f80c7eb47baf5acbe1c469b6563da4600b1eeb977b9495d7bd8"

      define_method(:install) do
        bin.install "weeks"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/weeks-app/weeks-cli/releases/download/v0.1.1/weeks_0.1.1_linux_x86_64.tar.gz"
      sha256 "779642c13fcf25c16bce3d14dbbb420e42edcc3bd5efb491faee587d447dda19"
      define_method(:install) do
        bin.install "weeks"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/weeks-app/weeks-cli/releases/download/v0.1.1/weeks_0.1.1_linux_arm64.tar.gz"
      sha256 "2e3bdbf456e8854d9b0fc40874523171db53ed8e7216e2f1888c05b96d1fd949"
      define_method(:install) do
        bin.install "weeks"
      end
    end
  end

  test do
    system "#{bin}/weeks", "version"
  end
end
